name: Build and Release PHP 7.4 (macOS)

on:
  workflow_dispatch:

jobs:
  build_and_release:
    name: Build and Release PHP 7.4 (macOS)
    runs-on: macos-latest
    env:
      PREFIX: /Applications/EServer/childApp/php/php-7.4
      PHP_VERSION: 7.4.33
      MACOSX_DEPLOYMENT_TARGET: 11.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool bison

      - name: Prepare EServer Library
        run: |
          sudo mkdir -p /Applications/EServer/Library
          sudo cp -R Library/* /Applications/EServer/Library/
          echo "===== /Applications/EServer/Library ====="
          ls -a /Applications/EServer/Library

      - name: Set Homebrew bison PATH
        run: |
          echo "bison version: $(bison --version | head -1)"
          BISON_PATH="$(brew --prefix bison)/bin"
          echo "bison path: $BISON_PATH"
          echo "$BISON_PATH" >> $GITHUB_PATH
          echo "new bison version: $($BISON_PATH/bison --version | head -1)"

      - name: Build PHP 7.4
        run: |
          chmod +x mac_arm64/php/php-7.4.sh
          ./mac_arm64/php/php-7.4.sh

      - name: Debug workspace
        run: |
          echo "===== PWD ====="
          pwd
          
          echo "===== ROOT LS ====="
          ls -la
          
          echo "===== FULL TREE ====="
          find . -maxdepth 3 -type f -print

      - name: Show PHP info
        run: |
          FILE="$PREFIX/bin/php"
          echo "=== PHP version ==="
          "$FILE" -v
          echo "=== PHP info (php -i) ==="
          "$FILE" -i
          echo "=== PHP info (phpinfo()) ==="
          "$FILE" -r "phpinfo();"
          echo "=== PHP modules ==="
          "$FILE" -m

      - name: Show file info
        run: |
          FILE="$PREFIX/bin/php"
          echo "=== file architectures ==="
          lipo -info "$FILE" 2>/dev/null || file "$FILE"
          echo "=== file minimum macOS version ==="
          otool -l "$FILE" | grep -A 3 LC_BUILD_VERSION
          echo "=== file dependencies ==="
          otool -L "$FILE"

      - name: Set artifact name
        run: echo "ARTIFACT_NAME=php-7.4.tar.xz" >> $GITHUB_ENV

      - name: Package artifact
        run: |
          tar -cJf "$ARTIFACT_NAME"  -C "$(dirname "$PREFIX")" "$(basename "$PREFIX")"

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          files: ${{ env.ARTIFACT_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
