name: Build and Release OpenSSL 3.5 (macOS)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. openssl-3.5.4)"
        required: true
  push:
    tags:
      - 'openssl-3.5-*'

jobs:
  build_and_release:
    name: Build and Release OpenSSL 3.5 (macOS)
    runs-on: macos-latest
    env:
      PREFIX: /Applications/EServer/Library/openssl@3.5
      OPENSSL_VERSION: 3.5.7
      MACOSX_DEPLOYMENT_TARGET: 11.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build OpenSSL
        run: |
          chmod +x mac_arm64/base/openssl@3.5.sh
          ./mac_arm64/base/openssl@3.5.sh

      - name: Debug workspace
        run: |
          echo "===== PWD ====="
          pwd
          
          echo "===== ROOT LS ====="
          ls -la
          
          echo "===== FULL TREE ====="
          find . -maxdepth 3 -type f -print

      - name: Show file info
        run: |
          FILE="$PREFIX/lib/libssl.dylib"
          echo "=== file architectures ==="
          lipo -info "$FILE"
          echo "=== file minimum macOS version ==="
          otool -l "$FILE" | grep -A 3 LC_BUILD_VERSION
          echo "=== file dependencies ==="
          otool -L "$FILE"

      - name: Set artifact name
        run: echo "ARTIFACT_NAME=openssl-3.5-macos-${OPENSSL_VERSION}.tar.gz" >> $GITHUB_ENV

      - name: Package artifact
        run: |
          tar -czf "$ARTIFACT_NAME"  -C "$(dirname "$PREFIX")" "$(basename "$PREFIX")"

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          files: ${{ env.ARTIFACT_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
