name: Build and Release PHP 7.2 (macOS)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. php-7.2.34)"
        required: true
  push:
    tags:
      - 'php-7.2-*'

jobs:
  build_and_release:
    name: Build and Release PHP 7.2 (macOS)
    runs-on: macos-latest
    env:
      PREFIX: /Applications/EServer/software/php/php-7.2
      PHP_VERSION: 7.2.34
      MACOSX_DEPLOYMENT_TARGET: 10.13

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare EServer Library
        run: |
          sudo mkdir -p /Applications/EServer/Library
          sudo cp -R Library/* /Applications/EServer/Library/
          echo "===== /Applications/EServer/Library ====="
          ls -a /Applications/EServer/Library

      - name: Build PHP 7.2
        run: |
          chmod +x mac_arm64/php/php-7.2.sh
          ./mac_arm64/php/php-7.2.sh

      - name: Debug workspace
        run: |
          echo "===== PWD ====="
          pwd
          
          echo "===== ROOT LS ====="
          ls -la
          
          echo "===== FULL TREE ====="
          find . -maxdepth 3 -type f -print

      - name: Show PHP info
        run: |
          FILE="$PREFIX/bin/php"
          echo "=== PHP version ==="
          "$FILE" -v
          echo "=== PHP modules ==="
          "$FILE" -m

      - name: Show file info
        run: |
          FILE="$PREFIX/bin/php"
          echo "=== file architectures ==="
          lipo -info "$FILE" 2>/dev/null || file "$FILE"
          echo "=== file minimum macOS version ==="
          otool -l "$FILE" | grep -A 3 LC_BUILD_VERSION
          echo "=== file dependencies ==="
          otool -L "$FILE"

      - name: Set artifact name
        run: echo "ARTIFACT_NAME=php-7.2-macos-${PHP_VERSION}.tar.gz" >> $GITHUB_ENV

      - name: Package artifact
        run: |
          tar -czf "$ARTIFACT_NAME"  -C "$(dirname "$PREFIX")" "$(basename "$PREFIX")"

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}
          files: ${{ env.ARTIFACT_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
